//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_BureauExpertiseAndEvaluation
{
    using System;
    
    public partial class funcZarplata_ResultF
    {
        public Nullable<int> Ид_сотрудника { get; set; }
        public string Фамилия { get; set; }
        public Nullable<decimal> Зарплата { get; set; }
    }
}
