//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_BureauExpertiseAndEvaluation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Квитанция
    {
        public int Номер { get; set; }
        public decimal Стоимость_экспертизы { get; set; }
        public decimal Оценка { get; set; }
        public string Решение { get; set; }
        public int Ид_диагностики { get; set; }
    
        public virtual Экспертиза_и_оценка Экспертиза_и_оценка { get; set; }
    }
}
