//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_BureauExpertiseAndEvaluation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Накладная
    {
        public int Номер { get; set; }
        public Nullable<System.DateTime> Дата_приёма { get; set; }
        public Nullable<System.DateTime> Срок_выполнения_диагностики { get; set; }
        public string Причина_обращения { get; set; }
        public string Состояние_объекта { get; set; }
        public string Статус { get; set; }
        public decimal Примерная_стоимость_экспертизы { get; set; }
        public int Ид_клиента { get; set; }
        public int Ид_сотрудника { get; set; }
        public int Ид_объекта { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Объекты_экспертизы Объекты_экспертизы { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
