//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_BureauExpertiseAndEvaluation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.Накладная = new HashSet<Накладная>();
        }
    
        public int Ид_сотрудника { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'.'MM'.'yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Дата_рождения { get; set; }
        public string Адрес_проживания { get; set; }
        public short Стаж { get; set; }
        public string Телефон { get; set; }
        public int Номер_трудовой_книжки { get; set; }
        public Nullable<long> ИНН { get; set; }
        public decimal Зарплата { get; set; }
        public int Серия_паспорта { get; set; }
        public int Номер_паспорта { get; set; }
        public int Ид_отдела { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Накладная> Накладная { get; set; }
        public virtual Отдел Отдел { get; set; }
    }
}
