//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_BureauExpertiseAndEvaluation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Техника
    {
        public Nullable<short> Год_производства { get; set; }
        public string Серийный_номер { get; set; }
        public Nullable<decimal> Цена_при_покупке { get; set; }
        public int Ид_объекта { get; set; }
        public string Компания_производитель { get; set; }
        public string Модель { get; set; }
    
        public virtual Объекты_экспертизы Объекты_экспертизы { get; set; }
    }
}
